apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.cluster-q9ln9.q9ln9.sandbox647.opentlc.com/rhtap/test:7f8d72c5d9dae6ef6ecd0b241bb760ff6901c22c@sha256:027bdd7e57dad9ea12774d5ed928cc6aae6402bc20e623d6927b5e603f9f034c
          name: container-image
